const sampleListings = [
  {
    title: "Leonardo Da Vinci, Mona Lisa, 1503–19",
    description: "Painted between 1503 and 1517, Da Vinci’s alluring portrait has been dogged by two questions since the day it was made: Who’s the subject and why is she smiling? A number of theories for the former have been proffered over the years: That she’s the wife of the Florentine merchant Francesco di Bartolomeo del Giocondo (ergo, the work’s alternative title, La Gioconda); that she's Leonardo’s mother, Caterina, conjured from Leonardo's boyhood memories of her; and finally, that it's a self-portrait in drag. As for that famous smile, its enigmatic quality has driven people crazy for centuries. Whatever the reason, Mona Lisa’s look of preternatural calm comports with the idealized landscape behind her, which dissolves into the distance through Leonardo’s use of atmospheric perspective.",
    image: "https://media.timeout.com/images/103166731/1024/768/image.webp",
    price: 1500,
    location: "leonardo@gmail.com",
    country: "United States",
  },
  {
    title: "Johannes Vermeer, Girl with a Pearl Earring, 1665",
    description: "Johannes Vermeer’s 1665 study of a young woman is startlingly real and startlingly modern, almost as if it were a photograph. This gets into the debate over whether or not Vermeer employed a pre-photographic device called a camera obscura to create the image. Leaving that aside, the sitter is unknown, though it’s been speculated that she might have been Vermeer's maid. He portrays her looking over her shoulder, locking her eyes with the viewer as if attempting to establish an intimate connection across the centuries. Technically speaking, Girl isn’t a portrait, but rather an example of the Dutch genre called a tronie—a headshot meant more as still life of facial features than as an attempt to capture a likeness.",
    image: "https://media.timeout.com/images/103166735/1024/768/image.webp",
    price: 1200,
    location: "johanes@gmail.com",
    country: "United States",
  },
  {
    title: "Vincent van Gogh, The Starry Night, 1889",
    description: "incent Van Gogh’s most popular painting, The Starry Night was created by Van Gogh at the asylum in Saint-Rémy, where he’d committed himself in 1889. Indeed, The Starry Night seems to reflect his turbulent state of mind at the time, as the night sky comes alive with swirls and orbs of frenetically applied brush marks springing from the yin and yang of his personal demons and awe of nature.",
    image: "https://media.timeout.com/images/103166739/1024/768/image.webp",
    price: 1000,
    location: "Vincent@gmail.com",
    country: "United States",
  },
  {
    title: "Gustav Klimt, The Kiss, 1907–1908",
    description: "Opulently gilded and extravagantly patterned, The Kiss, Gustav Klimt’s fin-de-siècle portrayal of intimacy, is a mix of Symbolism and Vienna Jugendstil, the Austrian variant of Art Nouveau. Klimt depicts his subjects as mythical figures made modern by luxuriant surfaces of up-to-the moment graphic motifs. The work is a highpoint of the artist’s Golden Phase between 1899 and 1910 when he often used gold leaf—a technique inspired by a 1903 trip to the Basilica di San Vitale in Ravenna, Italy, where he saw the church’s famed Byzantine mosaics.",
    image: "https://media.timeout.com/images/103166743/1024/768/image.webp",
    price: 2500,
    location: "gustav@gmail.com",
    country: "Italy",
  },
  {
    title: "Sandro Botticelli, The Birth of Venus, 1484–1486",
    description: "Botticelli’s The Birth of Venus was the first full-length, non-religious nude since antiquity, and was made for Lorenzo de Medici. It’s claimed that the figure of the Goddess of Love is modeled after one Simonetta Cattaneo Vespucci, whose favors were allegedly shared by Lorenzo and his younger brother, Giuliano. Venus is seen being blown ashore on a giant clamshell by the wind gods Zephyrus and Aura as the personification of spring awaits on land with a cloak. Unsurprisingly, Venus attracted the ire of Savonarola, the Dominican monk who led a fundamentalist crackdown on the secular tastes of the Florentines. His campaign included the infamous “Bonfire of the Vanities” of 1497, in which “profane” objects—cosmetics, artworks, books—were burned on a pyre. The Birth of Venus was itself scheduled for incineration, but somehow escaped destruction. Botticelli, though, was so freaked out by the incident that he gave up painting for a while.",
    image: "https://media.timeout.com/images/103166737/1024/768/image.webp",
    price: 800,
    location: "sandro@gmail.com",
    country: "United States",
  },
  {
    title: "James Abbott McNeill Whistler, Arrangement in Grey and Black No. 1, 1871",
    description:"Whistler’s Mother, or Arrangement in Grey and Black No. 1, as it’s actually titled, speaks to the artist’s ambition to pursue art for art’s sake. James Abbott McNeill Whistler painted the work in his London studio in 1871, and in it, the formality of portraiture becomes an essay in form. Whistler’s mother Anna is pictured as one of several elements locked into an arrangement of right angles. Her severe expression fits in with the rigidity of the composition, and it’s somewhat ironic to note that despite Whistler’s formalist intentions, the painting became a symbol of motherhood.",
    image: "https://media.timeout.com/images/103166741/1024/768/image.webp",
    price: 2000,
    location: "james@gmail.com",
    country: "Mexico",
  },
  {
    title: "Jan van Eyck, The Arnolfini Portrait, 1434",
    description: "One of the most significant works produced during the Northern Renaissance, this composition is believed to be one of the first paintings executed in oils. A full-length double portrait, it reputedly portrays an Italian merchant and a woman who may or may not be his bride. In 1934, the celebrated art historian Erwin Panofsky proposed that the painting is actually a wedding contract. What can be reliably said is that the piece is one of the first depictions of an interior using orthogonal perspective to create a sense of space that seems contiguous with the viewer’s own; it feels like a painting you could step into.",
    image: "https://media.timeout.com/images/103166745/1024/768/image.webp",
    price: 900,
    location: "janvan@gmail.com",
    country: "United States",
  },
  {
    title: "Hieronymus Bosch, The Garden of Earthly Delights, 1503–1515",
    description:"This fantastical triptych is generally considered a distant forerunner to Surrealism. In truth, it’s the expression of a late medieval artist who believed that God and the Devil, Heaven and Hell were real. Of the three scenes depicted, the left panel shows Christ presenting Eve to Adam, while the right one features the depredations of Hell; less clear is whether the center panel depicts Heaven. In Bosch’s perfervid vision of Hell, an enormous set of ears wielding a phallic knife attacks the damned, while a bird-beaked bug king with a chamber pot for a crown sits on its throne, devouring the doomed before promptly defecating them out again. This riot of symbolism has been largely impervious to interpretation, which may account for its widespread appeal.",
    image: "https://media.timeout.com/images/103166747/1024/768/image.webp",
    price: 3500,
    location: "hieronymus@gmail.com",
    country: "United States",
  },
  {
    title: "Georges Seurat, A Sunday Afternoon on the Island of La Grande Jatte, 1884–1886",
    description:"Georges Seurat’s masterpiece, evoking the Paris of La Belle Epoque, is actually depicting a working-class suburban scene well outside the city’s center. Seurat often made this milieu his subject, which differed from the bourgeois portrayals of his Impressionist contemporaries. Seurat abjured the capture-the-moment approach of Manet, Monet and Degas, going instead for the sense of timeless permanence found in Greek sculpture. And that is exactly what you get in this frieze-like processional of figures whose stillness is in keeping with Seurat’s aim of creating a classical landscape in modern form.",
    image:"https://media.timeout.com/images/105293264/1024/768/image.webp",
    price: 3000,
    location: "georges@gmail.com",
    country: "Switzerland",
  },
  {
    title: "Pablo Picasso, Les Demoiselles d’Avignon, 1907",
    description:"The ur-canvas of 20th-century art, Les Demoiselles d’Avignon ushered in the modern era by decisively breaking with the representational tradition of Western painting, incorporating allusions to the African masks that Picasso had seen in Paris's ethnographic museum at the Palais du Trocadro. Its compositional DNA also includes El Greco’s The Vision of Saint John (1608–14), now hanging in the Metropolitan Museum of Art. The women being depicted are actually prostitutes in a brothel in the artist's native Barcelona.",
    image:"https://media.timeout.com/images/103166750/1024/768/image.webp",
    price: 4000,
    location: "Serengeti@gmail.com",
    country: "Tanzania",
  },
  {
    title: "Pieter Bruegel the Elder, The Harvesters, 1565",
    description:"Bruegel’s fanfare for the common man is considered one of the defining works of Western art. This composition was one of six created on the theme of the seasons. The time is probably early September. A group of peasants on the left cut and bundle ripened wheat, while the on the right, another group takes their midday meal. One figure is sacked out under a tree with his pants unbuttoned. This attention to detail continues throughout the painting as a procession of ever-granular observations receding into space. It was extraordinary for a time when landscapes served mostly as backdrops for religious paintings.",
    image:"https://media.timeout.com/images/105222673/1024/768/image.webp",
    price: 1800,
    location: "Amsterdam@gmail.com",
    country: "Netherlands",
  },
  {
    title: "Édouard Manet, Le Déjeuner sur l’herbe, 1863",
    description:"Manet’s scene of picnicking Parisians caused a scandal when it debuted at the Salon des Refusés, the alternative exhibition made up of works rejected by the jurors of the annual Salon—the official art exhibition of the Académie des Beaux-Arts that set artistic standards in France. The most vociferous objections to Manet’s work centered on the depiction of a nude woman in the company of men dressed in contemporary clothes. Based on motifs borrowed from such Renaissance greats as Raphael and Giorgione, Le Déjeuner was a cheeky send up of classical figuration—an insolent mash-up of modern life and painting tradition.",
    image:"https://media.timeout.com/images/105222677/1024/768/image.webp",
    price: 10000,
    location: "Fiji@gmail.com",
    country: "Fiji",
  },
  {
    title: "Piet Mondrian, Composition with Red Blue and Yellow, 1930",
    description:"A small painting (18 inches by 18 inches) that packs a big art-historical punch, Mondrian’s work represents a radical distillation of form, color and composition to their basic components. Limiting his palette to the primary triad (red, yellow and blue), plus black and white, Mondrian applied pigment in flat unmixed patches in an arrangement of squares and rectangles that anticipated Minimalism.",
    image: "https://media.timeout.com/images/105222678/1024/768/image.webp",
    price: 1200,
    location: "Cotswolds@gmail.com",
    country: "United Kingdom",
  },
  {
    title: "Diego Rodríguez de Silva y Velázquez, Las Meninas, or The Family of King Philip IV",
    description:"A painting of a painting within a painting, Velázquez masterpiece consists of different themes rolled into one: A portrait of Spain’s royal family and retinue in Velázquez’s studio; a self-portrait; an almost art-for-art’s-sake display of bravura brush work; and an interior scene, offering glimpses into Velázquez’s working life. Las Meninas is also a treatise on the nature of seeing, as well as a riddle confounding viewers about what exactly they’re looking at. It’s the visual art equivalent of breaking the fourth wall—or in this case, the studio’s far wall on which there hangs a mirror reflecting the faces of the Spanish King and Queen. Immediately this suggests that the royal couple is on our side of the picture plane, raising the question of where we are in relationship to them. Meanwhile, Velázquez’s full length rendering of himself at his easel begs the question of whether he’s looking in a mirror to paint the picture. In other words, are the subjects of Las Meninas (all of whom are fixing their gaze outside of the frame), looking at us, or looking at themselves?",
    image: "https://media.timeout.com/images/105223155/1024/768/image.webp",
    price: 2200,
    location: "Boston@gmail.com",
    country: "United States",
  },
  {
    title: "Pablo Picasso, Guernica, 1937",
    description:"Perhaps Picasso’s best-known painting, Guernica is an antiwar cris de coeur occasioned by the 1937 bombing of the eponymous Basque city during the Spanish Civil War by German and Italian aircraft allied with Fascist leader Francisco Franco. The leftist government that opposed him commissioned Picasso to created the painting for the Spanish Pavillion at 1937 World’s Fair in Paris. When it closed, Guernica went on an international tour, before winding up at the Museum of Modern Art in New York. Picasso loaned the painting to MoMA with the stipulation that it be returned to his native Spain once democracy was restored—which it was in 1981, six years after Franco's death in 1975 (Picasso himself died two years before that.) Today, the painting is housed at the Museo Nacional Centro de Arte Reina Sofía in Madrid.",
    image:"https://media.timeout.com/images/105222680/1024/768/image.webp",
    price: 1800,
    location: "Bali@gmail.com",
    country: "Indonesia",
  },
  {
    title: "Claude Monet, Impression, Sunrise, 1874",
    description: "The defining figure of Impressionism, Monet virtually gave the movement its name with his painting of daybreak over the port of Le Havre, the artist’s hometown. Monet was known for his studies of light and color, and this canvas offers a splendid example with its flurry of brush strokes depicting the sun as an orange orb breaking through a hazy blue melding of water and sky.",
    image:"https://media.timeout.com/images/105222683/1024/768/image.webp",
    price: 1500,
    location: "Banff@gmail.com",
    country: "Canada",
  },
  {
    title: "Caspar David Friedrich, Wanderer above the Sea of Fog, 1819",
    description:"The worship of nature, or more precisely, the feeling of awe it inspired, was a signature of the Romantic style in art, and there is no better example on that score than this image of a hiker in the mountains, pausing on a rocky outcrop to take in his surroundings. His back is turned towards the viewer as if he were too enthralled with the landscape to turn around, but his pose offers a kind of over-the-shoulder view that draws us into vista as if we were seeing it through his eyes.",
    image:"https://media.timeout.com/images/105222684/1024/768/image.webp",
    price: 1600,
    location: "Miaji@gmail.com",
    country: "United States",
  },
  {
    title: "Théodore Géricault, The Raft of the Medusa, 1818–1819",
    description:"For sheer impact, it’s hard to top The Raft of the Medusa, in which Géricault took a contemporary news event and transformed it into a timeless icon. The backstory begins with the 1818 sinking of the French naval vessel off the coast of Africa, which left 147 sailors adrift on a hastily constructed raft. Of that number, only 15 remained after a 13-day ordeal at sea that included incidents of cannibalism among the desperate men. The larger-than-life-size painting, distinguished by a dramatic pyramidal composition, captures the moment the raft’s emaciated crew spots a rescue ship. Géricault undertook the massive canvas on his own, without anyone paying for it, and approached it much like an investigative reporter, interviewing survivors and making numerous detailed studies based on their testimony.",
    image: "https://media.timeout.com/images/105222685/1024/768/image.webp",
    price: 3000,
    location: "Phuket@gmail.com",
    country: "Thailand",
  },
  {
    title: "Edward Hopper, Nighthawks, 1942",
    description:"An iconic depiction of urban isolation, Nighthawks depicts a quarter of characters at night inside a greasy spoon with an expansive wraparound window that almost takes up the entire facade of the diner. Its brightly lit interior—the only source of illumination for the scene—floods the sidewalk and the surrounding buildings, which are otherwise dark. The restaurant's glass exterior creates a display-case effect that heightens the sense that the subjects (three customers and a counterman) are alone together. It's a study of alienation as the figures studiously ignore each other while losing themselves in a state of reverie or exhaustion. The diner was based on a long-demolished one in Hopper's Greenwich Village neighborhood, and some art historians have suggested that the painting as a whole may have been inspired by Vincent van Gogh’s Café Terrace at Night, which was on exhibit at a gallery Hopper frequented at same time he painted Nighthawks Also of note: The redheaded woman on the far right is the artist's wife Jo, who frequently modeled for him.",
    image: "https://media.timeout.com/images/105455060/1024/768/image.webp",
    price: 4000,
    location: "Scottish@gmail.com",
    country: "United Kingdom",
  },
  {
    title: "Marcel Duchamp, Nude Descending a Staircase, No. 2, 1912",
    description:"A stylistic mixture of Cubism and Futurism, Duchamp’s depiction of the titular subject in multiple exposure evokes a movement through time as well as space, and was inspired by the photographic motion studies of Eadweard Muybridge and Étienne-Jules Marey. The figure's planar construction drew the most ire, making the painting a lighting rod for ridicule. Nude was one of a handful of paintings Duchamp made before turning full time towards the conceptualist experiments (such as the Readymades and The Large Glass) for which he’s known.",
    image:"https://media.timeout.com/images/105455055/1024/768/image.webp",
    price: 5000,
    location: "Dubi@gmail.com",
    country: "United Arab Emirates",
  },
];

module.exports = { data: sampleListings };
